###
POST http://localhost:8080/v1/embeddings
Content-Type: application/json

{
    "model": "helloworld",
    "inputs": [
        "hello",
        "world"
    ]
}

### bad request
POST http://localhost:8080/v1/embeddings
Content-Type: application/json

{
  "model": "helloworld"
}
